### PR TITLE
Adding cache prefixes

### PR DESCRIPTION
**Pull request by alexgisby**
The cache class can now invisibly add prefixes to the items stored in the cache to prevent collisions!

See the README changes for an explanation.

### CODE REVIEW

**Review by craigharvi3 — APPROVED** [review]
Looks good to me 🏯

**Comment by steveculverwell** [comment]
⚔

**Review by lehmam03 — APPROVED** [review]
☕️

**Comment by alexgisby** [comment]
Thanks everyone! :)

**Pull request merged**
